-- Jetage India CMS schema.
--
-- `products.id` is the human slug already used everywhere in the app
-- (e.g. "hp-officejet-pro-9720") — kept as the primary key instead of adding
-- a surrogate integer, so every existing getProductById(id) call site and
-- every /products/[slug] URL keeps working unchanged.

create table if not exists categories (
  id          text primary key,
  name        text        not null,
  icon        text        not null default 'Package',
  description text        not null default '',
  sort_order  integer     not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists products (
  id               text        primary key,
  name             text        not null,
  short_name       text        not null default '',
  category_id      text        not null references categories (id) on update cascade,
  sub_category     text        not null default '',
  price            integer     not null default 0,
  mrp              integer     not null default 0,
  sku              text        not null default '',
  speed            text        not null default '',
  connectivity     jsonb       not null default '[]'::jsonb,
  duplex           boolean     not null default false,
  duty_cycle       text        not null default '',
  ideal_for        text        not null default '',
  description      text        not null default '',
  features         jsonb       not null default '[]'::jsonb,
  image            text        not null default '',
  images           jsonb       not null default '[]'::jsonb,
  badge            text,
  specs            jsonb       not null default '{}'::jsonb,
  warranty         text,
  weight           text,
  dimensions       text,
  first_page_out   text,
  resolution       text,
  paper_capacity   text,
  mobile_printing  jsonb       not null default '[]'::jsonb,
  -- Preserves the curated order the old static catalogue file had (the
  -- homepage/category grids showed products in file order, not alphabetical).
  sort_order       integer     not null default 0,
  -- Was previously derived from a hardcoded badge list; a real column lets
  -- an editor feature/unfeature a product without touching its marketing badge.
  featured         boolean     not null default false,
  status           text        not null default 'published'
                     check (status in ('draft', 'published')),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists products_category_idx on products (category_id);
create index if not exists products_status_idx   on products (status);
create index if not exists products_price_idx     on products (price);
create index if not exists products_featured_idx  on products (featured) where featured;

-- Full-text search over the fields a buyer actually types (model name, SKU,
-- feature list). Generated and stored so the index can't go stale.
alter table products drop column if exists search_vector;
alter table products
  add column search_vector tsvector
  generated always as (
    setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(short_name, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(sku, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(sub_category, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(description, '')), 'C') ||
    setweight(to_tsvector('english', coalesce(features::text, '')), 'D')
  ) stored;

create index if not exists products_search_idx on products using gin (search_vector);

create table if not exists blogs (
  slug             text        primary key,
  title            text        not null,
  meta_description text        not null default '',
  excerpt          text        not null default '',
  content          text        not null default '',
  category         text        not null default '',
  author           text        not null default 'Jetage Team',
  published_at     date        not null default current_date,
  read_time        text        not null default '',
  tags             jsonb       not null default '[]'::jsonb,
  featured         boolean     not null default false,
  cover_image      text,
  status           text        not null default 'published'
                     check (status in ('draft', 'published')),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists blogs_status_idx   on blogs (status, published_at desc);
create index if not exists blogs_featured_idx on blogs (featured) where featured;

-- Admin accounts. Password hashing uses node:crypto scrypt; the hash column
-- stores "salt:derivedKey" hex, so no password ever lands here in the clear.
create table if not exists admin_users (
  id            integer primary key generated by default as identity,
  email         text        not null unique,
  password_hash text        not null,
  name          text        not null default '',
  created_at    timestamptz not null default now()
);

-- Opaque session tokens. Only the SHA-256 of the cookie value is stored, so a
-- leaked database backup cannot be replayed as a live session.
create table if not exists sessions (
  token_hash text        primary key,
  user_id    integer     not null references admin_users (id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists sessions_expiry_idx on sessions (expires_at);

-- Every create/update/delete made through the admin, newest first. Append-only
-- from the app's side (nothing in src/lib ever updates or deletes a row here) —
-- it exists so a mistake is traceable, not so it can be edited.
create table if not exists audit_log (
  id           integer primary key generated by default as identity,
  actor_email  text        not null,
  action       text        not null check (action in ('create', 'update', 'delete')),
  resource     text        not null check (resource in ('product', 'blog')),
  record_id    text        not null,
  record_label text        not null,
  changes      jsonb,
  created_at   timestamptz not null default now()
);

create index if not exists audit_log_created_idx on audit_log (created_at desc);

-- updated_at is set explicitly by the write helpers in src/lib/cms.ts rather
-- than by a trigger — every write goes through those helpers, so a plpgsql
-- function would only add a second place to look when a timestamp is wrong.

-- ------------------------------------------------------------------ orders --
--
-- B2C retail checkout. Guest-only by design: there is no customer login and no
-- customer password anywhere in this schema. A buyer reaches their order
-- through `public_token`, which is emailed to them; the orders table itself is
-- the customer record, grouped by email in the admin.
--
-- Money is integer paise everywhere below, because that is the unit Razorpay
-- charges in. The catalogue stores whole rupees, so the conversion happens once
-- at order creation and never again — a float never touches a price.

create table if not exists orders (
  id                  integer primary key generated by default as identity,
  -- JI-26-000123. Human-quotable over the phone, which is how most of these
  -- will actually be chased up.
  order_no            text        not null unique,
  -- 256 bits of randomness. This is the whole of the buyer's authentication:
  -- knowing it proves they received the confirmation email.
  public_token        text        not null unique,

  email               text        not null,
  phone               text        not null,
  customer_name       text        not null,
  -- Snapshot, not a foreign key. Editing a saved address later must not
  -- silently rewrite where a past parcel was sent.
  ship_address        jsonb       not null default '{}'::jsonb,

  status              text        not null default 'pending'
                        check (status in ('pending','paid','packed','shipped','delivered','cancelled','refunded')),

  -- Prices in the catalogue are GST-inclusive and shipping is free, so
  -- subtotal == total. gst_paise is the tax *contained in* that total,
  -- back-computed at 18%, and exists so the invoice can show it.
  subtotal_paise      bigint      not null default 0,
  gst_paise           bigint      not null default 0,
  shipping_paise      bigint      not null default 0,
  total_paise         bigint      not null default 0,

  razorpay_order_id   text unique,
  razorpay_payment_id text,
  note                text,

  created_at          timestamptz not null default now(),
  paid_at             timestamptz,
  updated_at          timestamptz not null default now()
);

create index if not exists orders_email_idx  on orders (lower(email), created_at desc);
create index if not exists orders_status_idx on orders (status, created_at desc);

-- Line items snapshot name, sku and price. A product being renamed, repriced
-- or deleted must not change what an old invoice says was sold.
create table if not exists order_items (
  id               integer primary key generated by default as identity,
  order_id         integer not null references orders (id) on delete cascade,
  product_id       text,
  sku              text    not null default '',
  name             text    not null,
  image            text    not null default '',
  qty              integer not null check (qty > 0),
  unit_price_paise bigint  not null,
  line_total_paise bigint  not null
);

create index if not exists order_items_order_idx on order_items (order_id);

-- Append-only. The buyer's tracking page and the admin timeline read these same
-- rows, so "where is my order" cannot have two answers that disagree.
create table if not exists order_events (
  id         integer primary key generated by default as identity,
  order_id   integer     not null references orders (id) on delete cascade,
  type       text        not null,
  note       text,
  -- false = internal note, never rendered on the buyer's tracking page.
  is_public  boolean     not null default true,
  created_at timestamptz not null default now()
);

create index if not exists order_events_order_idx on order_events (order_id, created_at);

-- Order numbers come from a sequence rather than max(order_no)+1, which races
-- the moment two people check out in the same second.
create sequence if not exists order_no_seq start 1;

-- The tax lines an Indian invoice must actually show. Same total either way,
-- but a Chandigarh buyer gets CGST + SGST/UTGST and everyone else a single
-- IGST line. Stored per order rather than derived on read, because the
-- place of supply is a fact about the sale on the day it happened — moving
-- the business, or a buyer editing an address, must not restate old invoices.
alter table orders add column if not exists place_of_supply text not null default '';
alter table orders add column if not exists cgst_paise bigint not null default 0;
alter table orders add column if not exists sgst_paise bigint not null default 0;
alter table orders add column if not exists igst_paise bigint not null default 0;

-- The buyer's GSTIN, when they have one. Printers and toner are bought by
-- businesses as much as households, and a business buyer cannot claim input
-- credit unless their GSTIN is on the invoice — so not asking costs the sale.
-- Null means an ordinary consumer sale (B2C), which is most of them.
alter table orders add column if not exists buyer_gstin text;

-- Rate-limit counters, keyed on a SHA-256 rather than the thing being limited:
-- these exist to stop abuse and should not become a second list of everyone
-- who has used the site. In the database, not in memory, because on serverless
-- an in-process counter is bypassed by arriving at a different instance.
create table if not exists rate_limit (
  key_hash     text primary key,
  window_start timestamptz not null default now(),
  count        integer     not null default 0
);

-- Named counters. One row per series, incremented atomically.
--
-- Used for the GST invoice number, whose key carries the financial year
-- ("invoice:26-27"), so the series restarts at 1 every April on its own rather
-- than needing somebody to remember to reset it.
create table if not exists counters (
  name  text primary key,
  value integer not null default 0
);

-- Allocated when payment is captured, never at order creation — an abandoned
-- checkout must not burn a number out of a series that has to be consecutive.
alter table orders add column if not exists invoice_no text unique;

-- A parsed spreadsheet upload, waiting for someone to approve it.
--
-- The upload is never applied on the way in: it is parsed into a diff, stored
-- here, shown to a human, and only written when they press Apply. One sheet
-- with the price column shifted by a row would otherwise reprice the whole
-- catalogue silently, and nobody would notice until a customer queried it.
create table if not exists import_batches (
  id          integer primary key generated by default as identity,
  actor_email text        not null,
  rows        jsonb       not null,   -- the desired end state, one entry per sheet row
  summary     jsonb       not null,
  created_at  timestamptz not null default now(),
  applied_at  timestamptz,
  applied_by  text
);

create index if not exists import_batches_pending_idx
  on import_batches (created_at desc) where applied_at is null;

-- HSN, the code that says what a thing IS for tax. Rule 46 requires it on a
-- tax invoice, and the sales register needs it per line or the accountant
-- cannot file the HSN summary in GSTR-1. It lives on the product, because
-- that is where it is known once, and is snapshotted onto the order line at
-- the sale alongside name/sku/price: how a thing was classified is a fact
-- about the day it sold, and a later reclassification must not restate old
-- invoices. Blank is a legitimate state — no code beats a wrong one.
alter table products    add column if not exists hsn text not null default '';
alter table order_items add column if not exists hsn text not null default '';

-- The per-field diff the preview showed, kept with the batch.
--
-- It used to be computed, rendered, and thrown away, so the audit log said
-- only "changed by excel-import" for a batch that could touch every product
-- in the catalogue — the one path able to reprice 47 things at once recorded
-- the least about what it did. Storing it here also means the row that gets
-- audited is the diff the human actually approved, not one recomputed at
-- apply time against a catalogue that may have moved underneath.
alter table import_batches add column if not exists changes jsonb not null default '[]'::jsonb;

-- Every email this site tries to send, delivered or not.
--
-- "Did the buyer get their order confirmation?" had no answer except Vercel's
-- request log, which is retained on Vercel's schedule rather than ours and is
-- gone by the time anyone asks. Subject and recipient only: order mail
-- carries a name, a phone number and a delivery address, and none of that
-- needs a second copy in a table nobody reads until something goes wrong.
create table if not exists mail_log (
  id         integer primary key generated by default as identity,
  recipient  text        not null,
  subject    text        not null,
  template   text,
  sent       boolean     not null,
  error      text,
  created_at timestamptz not null default now()
);

create index if not exists mail_log_recent_idx on mail_log (created_at desc);
